workflows:
  ios-simulator-workflow:
    name: iOS Simulator Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS for simulator
        script: |
          flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/*.app

