workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods
          pod install
    artifacts:
      - build/ios/ipa


